accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>/follow', views.follow, name='follow'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name='root'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name='profile'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.list, name='list'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/comments/create/', views.create_comments, name='create_comments'),
    path('<int:post_id>/like/', views.like, name='like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')
    

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    content = models.CharField(max_length=140)
    image = models.ImageField(blank=True)
    # User와의 YGGR 1 (1:N)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # User와의 YGGR 2 (M:N)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True)
    
    def __str__(self):
        return '<{}: {}>'.format(self.id, self.content[:20])


class Comment(models.Model):
    content = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # fields = UserCreationForm.Meta.fields

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(
        label='content', 
        widget=forms.Textarea(attrs={
            'rows': '5',
            'cols': '50',
            'placeholder': '지금 뭘 하고 계신가요?',
            })
    )
    
    class Meta:
        model = Post
        # input을 만들 column을 list로 만들어 넣어줌.
        fields = ['content', 'image']
    
    
class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
        return redirect('root')
    else:
        form = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
        return redirect('root')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('root')
    

def profile(request, username):
    # User모델을 가져오는 방법
    # 1. from django.contrib.auth.models import User (비추)
    # 2. from django.conf import settings -> settings.AUTH_USER_MODEL (string형식)
    # 3. from django.contrib.auth import get_user_model 
    profile = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/profile.html', {'profile': profile})


def delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('root')
    else:
        return render(request, 'accounts/delete.html')


@login_required
def follow(request, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('profile', person.username)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostModelForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def create(request):
    # 'POST'요청이 오면,
    if request.method == 'POST':
        # 글을 작성하기
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:list')
    # 'GET'요청이 오면,
    else:
        # post를 작성하는 form을 가져와 template에서 보여줌. 
        form = PostModelForm()
        context = {
            'form': form
        }
        return render(request, 'posts/create.html', context)


@login_required
def list(request):
    posts = Post.objects.filter(user__in=request.user.followings.values('id')).order_by('-pk')
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/list.html', context)
    

@login_required
def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user != request.user:
        return render('posts:list')
    post.delete()
    return redirect('posts:list')


@login_required
def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user != request.user:
        return redirect('posts:list')
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    else:
        form = PostModelForm(instance=post)
        context = {
            'form':form
        }
        return render(request, 'posts/update.html', context)


@login_required
def create_comments(request, post_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()
        return redirect('posts:list')
        
 
@login_required  
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # 특정 유저가 특정 포스트를 좋아요 할때
    # 만약 좋아요가 되어 있다면, 좋아요를 해제한다.
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    # 아니면, 좋아요를 한다.
    else:
        post.like_users.add(request.user)
    return redirect('posts:list')

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% block body %}
  <h1>진짜로 탈퇴할꺼임? ㄹㅇ?</h1>
  <form method="post">
    {% csrf_token %}
    <button class='btn btn-secondary' type=submit>하지마ㅠㅠ</button>
  </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>로그인</h1>
  <form method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type=submit class='btn btn-primary'>로그인</button>
    {% endbuttons %}
  </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
  <h1>{{ profile.username }}
    {% if user != profile %}
      {% if user in profile.followers.all %}
        <a class="btn btn-warning" href="{% url 'accounts:follow' profile.id %}">언팔로우</a>
      {% else %}
        <a class="btn btn-success" href="{% url 'accounts:follow' profile.id %}">팔로우</a>
      {% endif %}
    {% endif %}
  </h1>
  {% if profile == request.user %}
    <a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원탈퇴</a>
  {% endif %}
  <div class="row">
    {% for post in profile.post_set.all %}
      <div class="col-4">
        <img src="{{ post.image.url }}" class="img-fluid"></img>
      </div>
    {% endfor %}
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>회원가입</h1>
  <form method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type=submit class='btn btn-primary'>회원가입</button>
    {% endbuttons %}
  </form>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>새로운 Post 작성하기</h1>
  <form method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type=submit class='btn btn-primary'>업로드</button>
    {% endbuttons %}
  </form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>작성한 Post</h1>
  {% for post in posts %}
    <div class="row justify-content-center">
      <div class="card col-7">
        <div class="card-header">
          <span><a href="{% url 'profile' post.user.username %}">{{ post.user }}</a></span>
        </div>
        <img src="{{ post.image.url }}" class="card-img-top" alt="random_image">
        <div class="card-body">
          <a href="{% url 'posts:like' post.id %}">
            {% if request.user in post.like_users.all %}
            <i class="fas fa-heart"></i>
            {% else %}
            <i class="far fa-heart"></i>
            {% endif %}
          </a>
          <p class="card-text">
            {{ post.like_users.count }}명이 좋아합니다.
          </p>
        </div>
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          {% if request.user == post.user %}
            <a class='btn btn-success' href="{% url 'posts:update' post.id %}">수정</a>
            <a class='btn btn-danger' href="{% url 'posts:delete' post.id %}">삭제</a>
          {% endif %}
          {% if post.comment_set %}
            <ul class="list-group">
              {% for comment in post.comment_set.all %}
                <li class="list-group-item">{{ comment.user }} | {{ comment.content }}</li>
              {% endfor %}
            </ul>
          {% endif %}
          <form method="post" action="{% url 'posts:create_comments' post.id %}">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <button type=submit class="btn btn-secondary">작성</button>
          </form>
        </div>
      </div>
    </div>
  {% endfor %}
  
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>Post 수정하기</h1>
  <form method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type=submit class='btn btn-success'>수정</button>
    {% endbuttons %}
  </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <title>INSTAGRAM</title>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container">
      {% block body %}
      {% endblock %}  
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'root' %}">
    <i class="fab fa-instagram" size="3x"></i>
    Instagram
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' user.username %}">{{ user }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:create' %}">새 글쓰기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>